### ISSUE TITLE
Healthchecks dependent on backend availability

### ISSUE THREAD

**Issue by dgl** [G-Research/geras#13]
Make `Info` return an error if unable to talk to backend (probably via calling `/api/version`, until OpenTSDB supports a better status API, see OpenTSDB/opentsdb #1742).

Also consider a HTTP endpoint that does similar for use with Kubernetes as a readiness probe.

**Comment by robincw-gr** [comment]
A small query would be a good readiness check. As issue #33 would introduce support querying for just the last datapoint, it is probably worth doing that work first.
