### ISSUE TITLE
Use /api/query/last for instantaneous queries

### ISSUE THREAD

**Issue by dgl** [G-Research/geras#33]
If a query is instantaneous then use `/api/query/last` to potentially reduce query cost http://opentsdb.net/docs/build/html/api_http/query/last.html

Will need a heuristic like mintime == maxtime and in last ~10 seconds to figure out if it's instantaneous, but that should be ok.

**Comment by robincw-gr** [comment]
If a minimum resolution for downsampling is introduced in issue #31 then that value can be used instead of the suggested 10sec

**Comment by dgl** [comment]
The heuristic is to figure out if the query is instantaneous, so it's just to deal with clocks not quite in sync. Using the downsampling value could lead to misleading results.

**Comment by robincw-gr** [comment]
Ah, clocks, that clarifies the reason for the 10sec.

**Comment by dgl** [comment]
Robin looked into this a bit, because last actually looks further back to find older timeseries (i.e. tags that exist but don't have recent data), it's actually more expensive. Don't think this is worth pursuing.
