### ISSUE TITLE
`{x="x|y"}` leaks OpenTSDB

### ISSUE THREAD

**Issue by dgl** [G-Research/geras#39]
We use `literal_or`, unfortunately that results in pipes becoming meaningful.

There doesn't appear to be a way to actually escape this properly, see code at https://github.com/OpenTSDB/opentsdb/blob/master/src/query/filter/TagVLiteralOrFilter.java#L72.

See http://opentsdb.net/docs/build/html/user_guide/query/filters.html

**Comment by dgl** [comment]
n.b.: Probably not a huge issue, I noticed this while considering how to optimise some label matches.

**Comment by stackedsax** [comment]
Hey there @dgl -- saw a couple of these issues and was wondering whether connecting with @itamarst might be useful.  Itamar has done a bit of work in the OpenTSDB codebase recently.  I thought that if you had suggestions for changes in OpenTSDB for geras to work more effectively, Itamar could take a look.

**Comment by dgl** [comment]
@stackedsax thanks, I think this is so low priority it's not worth doing anything in particular on the OpenTSDB side (we can workaround this easily in Geras), it's very unlikely anyone actually has a `|` in a tag value so the workaround shouldn't cost anything.

Adding a `literal` rather than `literal_or` filter would be nice (seems hard to retrofit escaping to `literal_or` now). There's some filter changes coming in OpenTSDB 3.0, which maybe this could fit into.
