### ISSUE TITLE
Errors are ignored

### ISSUE THREAD

**Issue by dgl** [G-Research/geras#48]
Geras doesn't actually look at the `ErrorMsg` response from opentsdb-goclient. However the fix for this is a bit tricky -- we now rely on not sending an error back when the metric name doesn't exist.

The errors we want to ignore look like `{"error":{"code":400,"message":"No such name for 'metrics': 'metric.name.here'","details":"[same as message]","trace":"net.opentsdb.BadRequestException: ... Caused by net.opentsdb.uid.NoSuchUniqueName..."}}`

The "net.opentsdb.uid.NosuchUniqueName" looks like the most useful way to filter, but probably just code == 400 is best rather than relying on implementation details.

**Comment by eswdd** [comment]
Pretty certain you can get code 400 for other malformed queries, which
might be unfortunate if we have bugs. The NoSuchUniqueName will apply to
tagks and exact tagvs also, which is probably fine for us.

**Comment by dgl** [comment]
This also applies to the Info healthcheck.

**Comment by dgl** [comment]
https://github.com/G-Research/geras/pull/51 will fix this.
