### ISSUE TITLE
Release Docker image

### ISSUE THREAD

**Issue by dgl** [G-Research/geras#60]
* Build on CircleCI
* Use GitHub package repo

**Comment by eswdd** [comment]
Simple answer is that we can't build on Circle CI and publish on GitHub package repository unless we're willing to use a personal account. When using a GitHub app token we get the error `unauthorized: This credential type is not supported for registry. Please use a Personal Access Token or GitHub Actions token instead`.

**Comment by eswdd** [comment]
Steps for testing:
* Created a new organisation: https://github.com/eswdd-test
* Created a new repo: https://github.com/eswdd-test/docker-test
* Created a new GitHub App within eswdd-test:
 * Name: docker-test-publisher
 * URL: https://github.com/eswdd-test/docker-test
 * Perms:
  * contents: RW
  * metadata: RO
 * Only install on this account
* Application id is 55935
* Install app on repo docker-test
* Installation id (from url) is 7067981
* Setup docker-test in Circle CI:
 * Configuration: https://github.com/eswdd-test/docker-test/blob/master/.circleci/config.yml
 * Provide PEM file to build by:
  * Generate (and save) private key for app
  * Encode file contents: `cat pemfile | base64`
  * Save base64 string as environment variable GITHUB_APP_KEY in Circle CI UI
 * https://github.com/eswdd-test/github-app-authenticator to get an app token given private key, app id and installation id (stripped out of whitelist-checker).

**Comment by dgl** [comment]
Presumably we can create a personal account which we treat like a service account and allow that access to the org, etc...

**Comment by eswdd** [comment]
So this leaves us with either publishing to GitHub Package repository using GitHub Actions or a personal account (which we'd have to pay a license fee for under the G-Research organisation).

Or we use CircleCI and publish to Docker Hub.

**Comment by eswdd** [comment]
In answer to your question, yes, but we'd have to pay for it - it's why we went the GitHub app route for the whitelist-checker.

**Comment by eswdd** [comment]
I suspect that initially at least the quickest way to get something out would be via Docker Hub.

**Comment by eswdd** [comment]
Steps for Docker Hub for completeness:
* Create new docker org: eswddtest
* Create new docker repo in org: docker-test
* Create new docker user: dockertestuploader
* Create new docker team: dockertest
* Create invite dockertestuploader into dockertest
* Create Grant RW perms to docker-test repo for dockertest team
* Create Add DOCKER_HUB_USER env var to circle ci env vars
* Create Add DOCKER_HUB_PASSWORD env var to circle ci env vars
* Create Update config: https://github.com/eswdd-test/docker-test/blob/abdfd6a1d8328e3b4f425e26f3f3c8196c97f595/.circleci/config.yml

Win: https://hub.docker.com/repository/docker/eswddtest/docker-test/tags?page=1

**Comment by eswdd** [comment]
Still means we need to manage a user in docker hub for a service account, but at least we don't need to pay whilst we have no private docker repositories.

**Comment by stackedsax** [comment]
I'd be happy to plug in some payment details if you need.  We also have 2318 seats left in the Github Organization, so no worries if you want to create another user as a service account.

In general, I'd be in favor of you doing the right thing/doing the thing you want to do, even if it costs us a bit of money.  I have budget precisely to help open source projects in situations like this!

**Comment by dgl** [comment]
We've done this using Docker Hub now, under the gresearch org.
