### ISSUE TITLE
Could not worked with thanos ?

### ISSUE THREAD

**Issue by Jamlee** [G-Research/geras#78]
I get error like below
![image](https://user-images.githubusercontent.com/5196641/82592617-c55f8e00-9bd3-11ea-870e-426b465619e8.png)

this is my docker-compose.yml, the geras is master version
![image](https://user-images.githubusercontent.com/5196641/82592801-09eb2980-9bd4-11ea-97fd-6fc66ce7d484.png)

**Comment by dgl** [comment]
It looks like this is the metric used for healthchecking that isn't found: https://github.com/G-Research/geras/blob/master/cmd/geras/main.go#L109

What version of OpenTSDB -- I'd expect this to not be failing? If you run with `-trace-dumpbody` and look at http://geras:19001/debug/requests?fam=grpc.Recv.Store&b=0&exp=1 (where geras is your geras container IP if needed) you'll see the requests which maybe have a better error message.

**Comment by Jamlee** [comment]
yes, i use the opentsdb v2.3.1, after i change the metric name, it worked. thanks buddy.
