### ISSUE TITLE
the character  "." is not handled correct when use geras with thanos_remote_read?

### ISSUE THREAD

**Issue by Jamlee** [G-Research/geras#79]
i get the error like below:
![image](https://user-images.githubusercontent.com/5196641/82645522-9124b580-9c45-11ea-875c-8bd9988be861.png)

there are my docker-compose.yml
![image](https://user-images.githubusercontent.com/5196641/82645579-ae598400-9c45-11ea-8fde-a2707675bddd.png)

**Comment by dgl** [comment]
There's a fix in #80, available by setting `-metrics-name-rewriting`, we weren't consistent in that we accepted the ':' form but returned '.' in `__name__`, which we can get away with if Thanos is used, but Prometheus does more validation in remote_read.

**Comment by Jamlee** [comment]
amazing, nice, good. give you my heart
